security:
    role_hierarchy:
        ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_RO:
            - ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_LIST
            - ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_DETAILS
        ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_RW:
            - ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_RO
#            - ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_CREATE
#            - ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_DELETE
#            - ROLE_SFS_TRANSLATION_ADMIN_TRANSLATIONS_UPDATE
